services:
  web:
    container_name: lumina-web
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG= True
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: lumina-db
    environment:
      POSTGRES_DB: lumina_db
      POSTGRES_USER: lumina_user
      POSTGRES_PASSWORD: lumina_password
    volumes:
      - lumina_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  lumina_db_data:


