site_name: Lumina - Análise de Sentimentos

# Configurações de navegação
nav:
  - Home: index.md

  - Configuração:
      - Configuração: configuracao/configuracao.md

  - Arquitetura: architecture/architecture.md

  - Jornada do Produto:
      - Documentação Visual: documentation/miro.md
      - Requisitos: documentation/requisitos.md
      - Product Backlog: documentation/productbacklog.md
      - Sprints: 
      documentation/sprints/sprint-0,1/Sprint_0_1.md
      documentation/sprints/sprint-2/Sprint_3.md
      documentation/sprints/sprint-3/Sprint_3.md
      documentation/sprints/sprint-4/Sprint_3.md
      - Releases Notes: documentation/releasesnotes.md

  - Protótipo: prototipo/prototipo.md

  - Políticas:
      - Plano de Comunicação: politicas/plano_comunicacao.md
      - Conduta: politicas/conduta.md
      - Contribuição: politicas/contribuicao.md
      - Commits: politicas/commits.md
      - Branchs: politicas/branchs.md
      - Issues: politicas/issue_tamplates.md

  - Registros:
      - Organização da equipe: registros/organizacaoequipe.md
      - Reuniões: registros/meetings.md
      - Estudos: registros/estudos.md

theme:
  # Trata-se de um tema personalizado, que foi desenvolvido a partir do tema Material
  name: material

  # Configurações de features - elementos que podem ser adicionados a documentação
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.full
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  # Configurações de idioma
  language: pt

  # Configurações de cores e fontes
  palette:
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono

# Configurações de texto no rodapé
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/unb-mds/2024-2-Squad05
