name: Upload CSV to Database

on:
  push:
    paths:
      - 'app/data/csv/*.csv'

jobs:
  find-latest-csv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Find latest CSV
        run: |
          import os
          import glob

          list_of_files = glob.glob('app/data/csv/*.csv')
          latest_file = max(list_of_files, key=os.path.getctime)
          print(os.path.getctime)
          print(latest_file)
        shell: python

