site_name: Documentação Analise de sentimentos
repo_url: https://github.com/unb-mds/2024-2-Squad05
extra_css:
  - stylesheets/extra.css

theme: 
  name: material
  favicon: assets/Squad05.png
  logo: assets/Squad05.png
  palette:
    primary: custom

nav:
  - Home: index.md
  - Visão do produto: visao_do_produto/visao_produto.md
  - Arquitetura: arquitetura/arquitetura.md
  - Protótipos: prototipo/prototipo.md

  - Sprints:
      - Sprint 0: sprints/sprint0.md
      - Sprint 1: sprints/sprint1.md
 


  # Adicionando link para Issues do GitHub
  - Ver Issues no GitHub: https://github.com/unb-mds/2024-2-Squad05/issues
